baseURL = 'https://caminosdepazupzlaflora.github.io/upz-la-flora/'
canonifyURLs = true
languageCode = 'es'
title = 'Caminos para la Paz y la Memoria Tywa Khe'
theme = 'mi-tema'

[params]
  storyFormUrl = ''
